version: "3.3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: bash -c " uvicorn app.main:app --host 0.0.0.0 --port 8000"                                              
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    image: backend_base
  test:
    image: backend_base
    command: python -m pytest
    links:
      - db
    env_file:
      - .env

